# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_EXPERIMENTAL="dependency_provisioners"
ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Worker Nodes
  NodeCount = 3

  (1..NodeCount).each do |i|

    config.vm.define "kstorage#{i}" do |node|

      node.vm.box = "generic/ubuntu2004"
      node.vm.box_check_update = false
      node.vm.box_version = "3.2.12"
      node.vm.hostname = "kstorage#{i}.example.com"
      node.vm.network "private_network", ip: "172.16.16.15#{i}"

      node.vm.provider "virtualbox" do |v|
        v.name = "kstorage#{i}"
        v.memory = 4096
        v.cpus = 1
      end


      node.vm.provision "shell", path: "bootstrap_kstorage.sh"

    end

  end

end
